// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function useWindowSize(param) {
  var initialState_width = window.innerWidth;
  var initialState_height = window.innerHeight;
  var initialState = {
    width: initialState_width,
    height: initialState_height
  };
  var match = React.useState(function () {
        return initialState;
      });
  var setWindowSize = match[1];
  React.useEffect((function () {
          var handleResize = function (param) {
            return Curry._1(setWindowSize, (function (param) {
                          return {
                                  width: window.innerWidth,
                                  height: window.innerHeight
                                };
                        }));
          };
          window.addEventListener("resize", handleResize);
          Curry._1(setWindowSize, (function (param) {
                  return {
                          width: window.innerWidth,
                          height: window.innerHeight
                        };
                }));
          return (function (param) {
                    window.removeEventListener("resize", handleResize);
                    
                  });
        }), [setWindowSize]);
  return match[0];
}

export {
  useWindowSize ,
  
}
/* react Not a pure module */
