// Generated by ReScript, PLEASE EDIT WITH CARE


var $$IntersectionObserverEntry = {};

var $$IntersectionObserver = {};

export {
  $$IntersectionObserverEntry ,
  $$IntersectionObserver ,
  
}
/* No side effect */
