// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";
import * as CatalogSearchHook$CatalogSearch from "../hooks/CatalogSearchHook.bs.js";

function CatalogListWrapper(Props) {
  var rootRef = Props.root;
  var children = Props.children;
  var match = CatalogSearchHook$CatalogSearch.useWindowSize(undefined);
  var cssHeight = String(Math.imul(match.height, 60) / 100 | 0) + "px";
  var useStyles = Styles.makeStyles({
        root: {
          height: cssHeight,
          overflowY: "scroll"
        }
      });
  var classes = useStyles();
  return React.createElement(Core.Paper, {
              children: children,
              className: classes.root,
              ref: rootRef
            });
}

var make = CatalogListWrapper;

export {
  make ,
  
}
/* react Not a pure module */
