// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";
import * as Colors from "@material-ui/core/colors";

var columns = [
  "Strain Descriptor",
  "Strain Summary",
  "Strain ID"
];

var useStyles = Styles.makeStyles({
      root: {
        borderBottom: "2px solid " + Colors.indigo[700],
        fontSize: "16px",
        fontWeight: "bold",
        letterSpacing: "0.15px"
      }
    });

function CatalogTableDisplay$CatalogTableHeader(Props) {
  var classes = useStyles();
  return React.createElement(Core.TableRow, {
              children: Belt_Array.mapWithIndex(columns, (function (i, c) {
                      return React.createElement(Core.TableCell, {
                                  children: c,
                                  className: classes.root,
                                  key: String(i)
                                });
                    }))
            });
}

var CatalogTableHeader = {
  columns: columns,
  useStyles: useStyles,
  make: CatalogTableDisplay$CatalogTableHeader
};

var useStyles$1 = Styles.makeStyles({
      root: {
        fontSize: "16px",
        fontWeight: "bold",
        letterSpacing: "0.15px"
      }
    });

function CatalogTableDisplay$CatalogTableItem(Props) {
  var item = Props.item;
  var classes = useStyles$1();
  return React.createElement(React.Fragment, undefined, React.createElement(Core.TableCell, {
                  children: item.label,
                  className: classes.root
                }), React.createElement(Core.TableCell, {
                  children: item.summary,
                  className: classes.root
                }), React.createElement(Core.TableCell, {
                  children: item.id,
                  className: classes.root
                }));
}

var CatalogTableItem = {
  useStyles: useStyles$1,
  make: CatalogTableDisplay$CatalogTableItem
};

export {
  CatalogTableHeader ,
  CatalogTableItem ,
  
}
/* useStyles Not a pure module */
