// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ErrorDisplay(Props) {
  var error = Props.error;
  var errorDisplay = "error ...... " + error.message;
  return React.createElement("h2", undefined, errorDisplay);
}

var make = ErrorDisplay;

export {
  make ,
  
}
/* react Not a pure module */
