// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Lab from "@material-ui/lab";
import * as Core from "@material-ui/core";

function LoadingDisplay(Props) {
  return React.createElement(Core.Box, {
              children: Belt_Array.makeBy(10, (function (i) {
                      return React.createElement(Lab.Skeleton, {
                                  height: 35,
                                  key: String(i)
                                });
                    })),
              mt: 4,
              mx: 8
            });
}

var make = LoadingDisplay;

export {
  make ,
  
}
/* react Not a pure module */
